# Generated by Django 6.0.6 on 2026-06-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location_type', models.CharField(choices=[('cafeteria', 'Cafeteria'), ('library', 'Library'), ('lecture_hall', 'Lecture Hall'), ('admin', 'Administration'), ('hostel', 'Hostel'), ('sports', 'Sports'), ('clinic', 'Clinic'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location_x', models.FloatField(help_text='X position as percentage (0.0 to 1.0)')),
                ('location_y', models.FloatField(help_text='Y position as percentage (0.0 to 1.0)')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
