# Generated by Django 6.0.6 on 2026-06-06 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['order', 'name']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='special_instructions',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='created_at',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='reserved_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='0 means unlimited'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('preparing', 'Being Prepared'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafeteria.menuitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
